feat(fix) : Pagination with only one page inside
schorfES/caroucssel pull request #81
Opened 2020-09-11 15:15 UTC by ravi-kolla

2020-09-17 08:45 UTC, schorfES requested changes
Hi @ravi-kolla and thank you for your contribution. ❤️ 

The PR is currently failing because of some detected security vulnerabilities during the CI validation and tests. I am going to fix these errors.

I am currently working on a new release. These new features/updates are located in a [feature/next](https://github.com/schorfES/caroucssel/tree/feature/next). Can you please use that branch as a basis for you changes right now?

Can you also add some tests for this fix to test if the rendering of the pagination runs properly? I think about these test cases:

* Renders no pagination if a pagination has only one page
* Re-renders the pagination when a the amount of pages changes (by viewport/item size changes)
> * from state rendered with pagination to state without
> * from state rendered without pagination to state with

2020-09-17 08:45 UTC, schorfES commented on src/index.js
> +			const pagination = __render(hasPagination, {
The render function expects a template. You're passing the setting if the pagination feature should be enabled.

```suggestion
			const pagination = __render(paginationTempate, {
```

2020-09-17 08:45 UTC, schorfES commented on src/index.js
> +		} else {
I would suggest to handle it codewise a bit differently. There is no need for a if/else statement.

```
if (pages.length < 2) {
  return;
}
```

2020-09-21 10:14 UTC, schorfES commented
Hi @ravi-kolla, I've added the described changes and merged you commit's into the `feature/next` branch. Thank you for your contribution.

2020-09-21 10:14 UTC, closed without merging

2020-09-21 10:18 UTC, ravi-kolla commented
Thank you @schorfES 👍

2020-09-21 19:42 UTC, schorfES commented
There is a pre-release available at npm using caroucssel@next

> Am 21.09.2020 um 12:18 schrieb Ravi Teja Kolla <notifications@github.com>:
> 
> Thank you @schorfES 👍
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.